### ISSUE TITLE
"Proof." folding symbol not  rendered in Firefox 71 on and Chromium on Gentoo Linux

### ISSUE THREAD

**Issue by chdoc** [palmskog/coqdocjs#5]
As the title says:

Firefox:
![Screenshot_2020-01-05 Huffman Huffman](https://user-images.githubusercontent.com/20443222/71782982-c3a87b80-2fe0-11ea-8317-eacb8b5a8d4b.png)

Chromium looks similar.

And this is after allowing the requests to google fonts, something I would not do/use myself.

**Comment by palmskog** [comment]
This should be fixed now, I switched to symbols that seem to work in almost any Linux and Android browser. Please reopen if it still doesn't work.
