### ISSUE TITLE
Deploy branch: master or gh-pages?

### ISSUE THREAD

**Issue by liyishuai** [palmskog/coqdocjs#6]
https://github.com/palmskog/coqdocjs/blob/98c32574001666edb4f8c0182eca8e595123f435/README.md#L41-L42
This implies pushing to `master` branch, which is feasible for stable releases. If we document dev version, maybe `gh-pages` is a better branch to consider.

**Comment by palmskog** [comment]
I agree it's not obvious what to use, I would opt for project maintainers to take their pick of branch containing documentation. I'll remove the stuff about pushing.

**Comment by palmskog** [comment]
Now the README and all code is agnostic to whether one uses `gh-pages` or something else, so closing this.
